"""Protocol export service — generate DOCX and PDF research protocol documents."""

from __future__ import annotations

import io
import logging
from datetime import datetime
from typing import Any, Literal

from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

from app.services.citation_extractor import (
    extract_citations_from_messages,
    format_vancouver_bibliography,
)

_logger = logging.getLogger(__name__)

# Unicode -> ASCII replacements for fpdf2 built-in fonts (no Unicode support)
_UNICODE_MAP: dict[str, str] = {
    "\u2014": "--",   # em-dash
    "\u2013": "-",    # en-dash
    "\u2026": "...",  # ellipsis
    "\u2018": "'",    # left single quote
    "\u2019": "'",    # right single quote
    "\u201c": '"',    # left double quote
    "\u201d": '"',    # right double quote
    "\u00b1": "+/-",  # plus-minus
    "\u2248": "~",    # approximately equal
    "\u2264": "<=",   # less than or equal
    "\u2265": ">=",   # greater than or equal
    "\u03b1": "alpha",    # α
    "\u03b2": "beta",     # β
    "\u03b3": "gamma",    # γ
    "\u03b4": "delta",    # δ
    "\u03bc": "mu",       # μ
    "\u03c3": "sigma",    # σ
    "\u03c7": "chi",      # χ
    "\u00b2": "^2",   # superscript 2
    "\u2192": "->",   # right arrow
}


def _sanitize_for_pdf(text: str) -> str:
    """Replace Unicode characters unsupported by fpdf2 built-in fonts."""
    for char, replacement in _UNICODE_MAP.items():
        text = text.replace(char, replacement)
    # Strip any remaining non-latin1 characters
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _parse_summary_sections(summary_text: str) -> list[dict[str, Any]]:
    """Parse a markdown-formatted summary into heading/content pairs.

    The LLM summary uses ``## Heading`` markdown headings.  We split on those
    and return each as a separate section.  Content between the start of the
    text and the first heading (if any) is returned under a generic heading.
    """
    import re as _re

    # Split on markdown H2 lines (## Heading)
    parts = _re.split(r"^##\s+", summary_text, flags=_re.MULTILINE)

    sections: list[dict[str, Any]] = []

    # Text before the first ## heading (if any)
    preamble = parts[0].strip()
    if preamble:
        sections.append({"heading": "Overview", "content": preamble})

    for part in parts[1:]:
        # First line is the heading, rest is content
        lines = part.split("\n", 1)
        heading = lines[0].strip().rstrip("#").strip()
        content = lines[1].strip() if len(lines) > 1 else ""
        if heading and content:
            sections.append({"heading": heading, "content": content})

    return sections


def _build_protocol_sections(
    summary_text: str,
    messages: list[dict[str, str]],
    session_id: str,
) -> list[dict[str, Any]]:
    """Build structured protocol sections from the LLM-generated summary.

    The summary is already formatted with ``## Section`` headings by the LLM
    (Background, Research Question, Study Design, Statistical Analysis, etc.).
    We parse those into proper document sections.  Raw conversation messages
    are only used to extract citations for a bibliography -- the body text
    comes entirely from the synthesised summary.
    """
    # Try to parse structured sections from the summary
    parsed = _parse_summary_sections(summary_text)

    if len(parsed) >= 2:
        # Successfully parsed structured summary -- use it directly
        sections = list(parsed)
    else:
        # Fallback: summary wasn't structured (shouldn't happen with current
        # prompt, but be defensive) -- put it under a single heading
        sections = [{"heading": "Research Protocol Summary", "content": summary_text}]

    # Append a bibliography from extracted citations (links in the messages)
    citations = extract_citations_from_messages(messages)
    bibliography = format_vancouver_bibliography(citations)
    if bibliography:
        # Avoid duplicate references section if the summary already has one
        existing_headings = {s["heading"].lower() for s in sections}
        if "references" not in existing_headings:
            sections.append({"heading": "References", "content": bibliography})

    return sections


def generate_docx(
    summary_text: str,
    messages: list[dict[str, str]],
    session_id: str,
) -> bytes:
    """Generate a DOCX protocol document and return the file bytes."""
    doc = Document()

    # Title
    title = doc.add_heading("Research Protocol", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Metadata
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = meta.add_run(
        f"Generated: {datetime.now().strftime('%B %d, %Y')}\n"
        f"Session: {session_id[:8]}\n"
        "Generated by: ProtoCol"
    )
    run.font.size = Pt(10)
    run.font.italic = True

    doc.add_paragraph()  # spacer

    # Sections
    sections = _build_protocol_sections(summary_text, messages, session_id)
    for section in sections:
        doc.add_heading(section["heading"], level=1)
        doc.add_paragraph(section["content"])

    # Disclaimer
    doc.add_paragraph()
    disclaimer = doc.add_paragraph()
    disclaimer_run = disclaimer.add_run(
        "Disclaimer: This protocol was generated with AI assistance. "
        "All statistical recommendations and study design decisions should be "
        "verified with a qualified biostatistician before submission to an IRB "
        "or ethics committee."
    )
    disclaimer_run.font.size = Pt(9)
    disclaimer_run.font.italic = True

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


def _generate_html(
    summary_text: str,
    messages: list[dict[str, str]],
    session_id: str,
) -> str:
    """Generate an HTML document for PDF conversion."""
    sections = _build_protocol_sections(summary_text, messages, session_id)
    date_str = datetime.now().strftime("%B %d, %Y")

    section_html = ""
    for section in sections:
        # Escape basic HTML entities and preserve newlines
        content = (
            section["content"]
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\n\n", "</p><p>")
            .replace("\n", "<br>")
        )
        section_html += f"""
        <h2>{section['heading']}</h2>
        <p>{content}</p>
        """

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
    @page {{
        size: A4;
        margin: 2.5cm;
    }}
    body {{
        font-family: 'Georgia', 'Times New Roman', serif;
        font-size: 11pt;
        line-height: 1.6;
        color: #1a1a1a;
    }}
    h1 {{
        text-align: center;
        font-size: 22pt;
        margin-bottom: 0.5em;
        color: #2c3e50;
    }}
    .meta {{
        text-align: center;
        font-size: 9pt;
        color: #666;
        font-style: italic;
        margin-bottom: 2em;
    }}
    h2 {{
        font-size: 14pt;
        color: #2c3e50;
        border-bottom: 1px solid #bdc3c7;
        padding-bottom: 0.3em;
        margin-top: 1.5em;
    }}
    p {{
        text-align: justify;
        margin-bottom: 0.8em;
    }}
    .disclaimer {{
        font-size: 9pt;
        color: #888;
        font-style: italic;
        border-top: 1px solid #ddd;
        padding-top: 1em;
        margin-top: 3em;
    }}
</style>
</head>
<body>
    <h1>Research Protocol</h1>
    <div class="meta">
        Generated: {date_str} | Session: {session_id[:8]}<br>
        ProtoCol
    </div>
    {section_html}
    <p class="disclaimer">
        Disclaimer: This protocol was generated with AI assistance.
        All statistical recommendations and study design decisions should be
        verified with a qualified biostatistician before submission to an IRB
        or ethics committee.
    </p>
</body>
</html>"""


def generate_pdf(
    summary_text: str,
    messages: list[dict[str, str]],
    session_id: str,
) -> bytes:
    """Generate a PDF protocol document using fpdf2 (pure Python) and return the file bytes."""
    from fpdf import FPDF

    sections = _build_protocol_sections(summary_text, messages, session_id)
    date_str = datetime.now().strftime("%B %d, %Y")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=25)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 22)
    pdf.cell(0, 12, "Research Protocol", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(4)

    # Metadata
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, f"Generated: {date_str}  |  Session: {session_id[:8]}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.cell(0, 5, "ProtoCol", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(8)

    # Sections
    for section in sections:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(44, 62, 80)
        pdf.cell(0, 10, section["heading"], new_x="LMARGIN", new_y="NEXT")
        # Separator line
        pdf.set_draw_color(189, 195, 199)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
        pdf.ln(3)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(26, 26, 26)
        pdf.multi_cell(0, 5.5, _sanitize_for_pdf(section["content"]))
        pdf.ln(4)

    # Disclaimer
    pdf.ln(8)
    pdf.set_draw_color(220, 220, 220)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(136, 136, 136)
    pdf.multi_cell(
        0, 4.5,
        "Disclaimer: This protocol was generated with AI assistance. "
        "All statistical recommendations and study design decisions should be "
        "verified with a qualified biostatistician before submission to an IRB "
        "or ethics committee.",
    )

    return bytes(pdf.output())


def generate_protocol(
    summary_text: str,
    messages: list[dict[str, str]],
    session_id: str,
    format: Literal["docx", "pdf"] = "docx",
) -> tuple[bytes, str, str]:
    """Generate a protocol document.

    Returns (file_bytes, content_type, filename).
    """
    short_id = session_id[:8]

    if format == "pdf":
        data = generate_pdf(summary_text, messages, session_id)
        return data, "application/pdf", f"protocol-{short_id}.pdf"

    data = generate_docx(summary_text, messages, session_id)
    return (
        data,
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        f"protocol-{short_id}.docx",
    )
